from flask import Flask, request, jsonify, make_response
from flask_cors import CORS
import re
# import spacy removed to fix hang
import os
import traceback
from datetime import datetime
import json
import logging
import threading
import hashlib
from groq import Groq
import ollama as ollama_client
import base64
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

print(f"--- SERVER STARTING FROM: {os.path.abspath(__file__)} ---", flush=True)
app = Flask(__name__)
CORS(app)

# Load SpaCy model - disabled to fix hang
nlp = None

TECH_SKILLS = [
    # Languages & Core
    'Python', 'Java', 'C++', 'C', 'C#', 'JavaScript', 'TypeScript', 'Go', 'Rust', 'Swift', 'Kotlin', 'PHP', 'Ruby', 'Dart', 'Scala', 'Haskell', 'Julia', 'MATLAB', 'R', 'Perl', 'Solidity', 'Zig',
    # Frontend
    'React', 'Next.js', 'NextJS', 'Vue.js', 'VueJS', 'Angular', 'Svelte', 'SolidJS', 'Remix', 'Gatsby', 'HTML5', 'CSS3', 'Sass', 'Tailwind', 'Material UI', 'MUI', 'Chakra UI', 'Styled Components', 'Bootstrap', 'Redux', 'Zustand', 'Recoil', 'MobX', 'jQuery', 'Webpack', 'Vite', 'Babel',
    # Backend & Modules
    'Node.js', 'NodeJS', 'Express', 'Fastify', 'NestJS', 'Deno', 'Bun', 'Django', 'Flask', 'FastAPI', 'Spring Boot', 'Spring', 'Hibernate', 'Laravel', 'Symfony', 'CodeIgniter', 'Rails', 'Asp.NET', 'Entity Framework', 'Ruby on Rails', 'Golang', 'Gin', 'Echo', 'Fiber',
    # Mobile
    'Flutter', 'React Native', 'Ionic', 'Apache Cordova', 'Xamarin', 'SwiftUI', 'Android SDK', 'Jetpack Compose', 'Obj-C',
    # Databases & Cache
    'MongoDB', 'PostgreSQL', 'MySQL', 'SQLite', 'MariaDB', 'OracleDB', 'Cassandra', 'Redis', 'Elasticsearch', 'DynamoDB', 'Firebase', 'Supabase', 'PocketBase', 'Prisma', 'Drizzle', 'Mongoose', 'TypeORM', 'GraphQL', 'Apollo', 'Hasura',
    # Cloud & DevOps
    'AWS', 'Azure', 'GCP', 'Google Cloud', 'Docker', 'Kubernetes', 'K8s', 'Terraform', 'Ansible', 'Jenkins', 'GitHub Actions', 'GitLab CI', 'CircleCI', 'Vercel', 'Netlify', 'Nginx', 'Apache', 'Linux', 'Ubuntu', 'Debian', 'CentOS', 'Prometheus', 'Grafana', 'Serverless', 'Lambda',
    # AI & Data
    'Machine Learning', 'Deep Learning', 'NLP', 'Computer Vision', 'Data Science', 'PyTorch', 'TensorFlow', 'Keras', 'Scikit-learn', 'Pandas', 'NumPy', 'Matplotlib', 'Seaborn', 'OpenCV', 'LangChain', 'LlamaIndex', 'HuggingFace', 'OpenAI', 'Gemini', 'GANs', 'Transformers', 'Spark', 'Hadoop',
    # Engineering & Hardware (ECE/EEE/MECH/CIVIL)
    'VHDL', 'Verilog', 'PLC', 'SCADA', 'Keil', 'Proteus', 'LabVIEW', 'Embedded C', 'Arduino', 'Raspberry Pi', 'AutoCAD', 'SolidWorks', 'Revit', 'ANSYS', 'CATIA', 'Simulink', 'Staad Pro', 'Aspen HYSYS', 'Bioinformatics', 'Verilog HDL', 'Microcontrollers', 'VLSI', 'Digital Electronics',
    # Tools & Concepts
    'Git', 'SVN', 'REST API', 'gRPC', 'WebSockets', 'OAuth', 'JWT', 'Microservices', 'Docker Compose', 'Postman', 'Vagrant', 'TDD', 'Agile', 'Scrum', 'Jira', 'Figma', 'Canvas', 'Three.js', 'Web3', 'Ethereum', 'Blockchain'
]

SECTION_KEYWORDS = {
    'experience': ['EXPERIENCE', 'WORK HISTORY', 'EMPLOYMENT', 'PROFESSIONAL EXPERIENCE', 'INTERNSHIPS', 'TRAINING'],
    'education': ['EDUCATION', 'ACADEMIC BACKGROUND', 'QUALIFICATIONS', 'SCHOLASTIC', 'ACADEMICS'],
    'projects': ['PROJECTS', 'PERSONAL PROJECTS', 'ACADEMIC PROJECTS', 'TECHNICAL PROJECTS', 'KEY PROJECTS'],
    'skills': ['SKILLS', 'TECHNICAL SKILLS', 'CORE COMPETENCIES', 'TECHNOLOGIES', 'TECH STACK', 'SKILLSET'],
    'achievements': ['ACHIEVEMENTS', 'ACHIVEMENTS', 'AWARDS', 'HONORS', 'ACCOMPLISHMENTS', 'CO-CURRICULAR', 'EXTRACURRICULAR'],
    'certifications': ['CERTIFICATIONS', 'LICENSES', 'CERTIFICATES', 'COURSES', 'TRAINING', 'CERTIFICATION'],
    'summary': ['SUMMARY', 'PROFESSIONAL SUMMARY', 'PROFILE', 'ABOUT ME', 'OBJECTIVE', 'CAREER GOAL', 'STRENGTHS']
}

def clean_text(text):
    """Deeply sanitize text to remove PDF noise and improve parsing quality."""
    if not text: return ""
    text = re.sub(r'[^\x00-\x7f]', r' ', text)
    text = re.sub(r'(?i)Page\s*\d+\s*(of|/)\s*\d+', ' ', text)
    text = re.sub(r'(?i)\bPage\s*\d+\b', ' ', text)
    text = re.sub(r'(?i)Generated by\s*[\w\+]+', ' ', text)
    text = re.sub(r'(?i)Resume of\s*[\w\s]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    text = re.sub(r'[ \t]{2,}', ' ', text)
    text = re.sub(r'[\.\-\_\=]{4,}', ' ', text)
    return text.strip()

def segment_resume(text):
    lines = text.split('\n')
    segments = {k: [] for k in SECTION_KEYWORDS.keys()}
    segments['header'] = []
    current_section = 'header'
    for line in lines:
        clean_line = line.strip()
        if not clean_line: continue
        found_header = False
        for section, keywords in SECTION_KEYWORDS.items():
            if any(kw in clean_line.upper() for kw in keywords) and len(clean_line) < 40:
                current_section = section
                segments[current_section].append(clean_line)
                found_header = True
                break
        if not found_header:
            segments[current_section].append(clean_line)
    return {k: '\n'.join(v) for k, v in segments.items()}

def extract_skills(segments, full_text):
    skills_text = segments.get('skills', '') + '\n' + segments.get('projects', '')
    if not skills_text.strip(): skills_text = full_text
    found_skills = []
    sorted_skills = sorted(TECH_SKILLS, key=len, reverse=True)
    for skill in sorted_skills:
        pattern = r'(?i)(?<![a-zA-Z0-9#+])' + re.escape(skill) + r'(?![a-zA-Z0-9#+])'
        if re.search(pattern, skills_text):
            found_skills.append(skill)
    return list(set(found_skills))

def extract_education(segments, full_text):
    text = segments.get('education', '')
    if not text.strip(): text = full_text
    education = []
    degree_patterns = [
        r"(?i)(Bachelor|B\.E|B\.Tech|Degree|Master|M\.E|M\.Tech|PhD|Doctorate)\s+(of|in)\s+[\w\s\-]{3,40}",
        r"(?i)\b(B\.Tech|B\.E|M\.Tech|M\.E|MCA|BCA|B\.Sc|M\.Sc)\b"
    ]
    lines = text.split('\n')
    for line in lines:
        for pattern in degree_patterns:
            match = re.search(pattern, line)
            if match:
                grade_match = re.search(r"(\d+\.\d+)\s*/\s*10(\.0)?|grade:\s*(\d+\.\d+)", line, re.I)
                grade = grade_match.group(1) or grade_match.group(3) if grade_match else None
                year_match = re.search(r"\b(20\d{2})\b", line)
                year = year_match.group(1) if year_match else None
                institution = "Name not detected"
                if re.search(r"(?i)(University|College|Institute|School|Academy)", line):
                    institution = line.split(match.group(0))[-1].strip() or line.split(match.group(0))[0].strip()
                education.append({
                    "degree": match.group(0).strip(),
                    "institution": institution.strip(', '),
                    "grade": grade,
                    "year": year
                })
                break
    return education[:3]

def extract_links(text):
    links = {"linkedin": "", "github": "", "portfolio": ""}
    linkedin = re.search(r'(https?://(www\.)?linkedin\.com/in/[a-zA-Z0-9\-_%]+)', text)
    github = re.search(r'(https?://(www\.)?github\.com/[a-zA-Z0-9\-_%]+)', text)
    if linkedin: links["linkedin"] = linkedin.group(1)
    if github: links["github"] = github.group(1)
    return links

def extract_projects(segments):
    text = segments.get('projects', '')
    if not text: return []
    lines = text.split('\n')
    projects = []
    current_project = None
    for i, line in enumerate(lines):
        clean = line.strip()
        if not clean: continue
        is_header = any(kw in clean.upper() for kw in SECTION_KEYWORDS['projects'])
        if is_header and len(clean) < 30: continue
        is_bullet = clean.startswith(('•', '-', '*', '➢'))
        is_new = is_bullet or (len(clean) < 60 and clean.isupper() and not clean.startswith('.'))
        if is_new:
            if current_project: projects.append(current_project)
            title = clean.lstrip('•-*➢ ').strip()
            current_project = {"title": title, "description": "", "technologies": [], "link": ""}
        elif current_project:
            tech_match = re.search(r'(?i)(Tech|Stack|Tools|Languages)[:\-]\s*(.*)', clean)
            if tech_match:
                techs = re.split(r'[,|/]', tech_match.group(2))
                current_project["technologies"].extend([t.strip() for t in techs if t.strip()])
            else:
                current_project["description"] += " " + clean.lstrip('.').strip()
    if current_project: projects.append(current_project)
    for p in projects:
        p["description"] = p["description"].strip()
        found_techs = [s for s in TECH_SKILLS if s.lower() in (p["description"] + " " + p["title"]).lower()]
        p["technologies"] = list(set(p["technologies"] + found_techs))
    return projects[:4]

def extract_summary(segments, full_text):
    text = segments.get('summary', '')
    if len(text.strip()) > 50: return re.sub(r'\s+', ' ', text).strip()
    header_text = segments.get('header', '')
    lines = header_text.split('\n')
    for line in lines:
        if 50 < len(line.strip()) < 300: return line.strip()
    return ""

def extract_certifications(segments):
    text = segments.get('certifications', '')
    if not text: return []
    lines = text.split('\n')
    certs = []
    for line in lines:
        clean = line.strip().lstrip('•-*➢ ').strip()
        if 5 < len(clean) < 100:
            if not any(kw in clean.upper() for kw in SECTION_KEYWORDS['certifications']):
                certs.append(clean)
    return list(set(certs))[:8]

def extract_soft_skills(full_text):
    soft_skills = ['Leadership', 'Teamwork', 'Communication', 'Problem Solving', 'Adaptability', 'Critical Thinking', 'Collaboration']
    return [s for s in soft_skills if re.search(r'(?i)\b' + s + r'\b', full_text)]

# --- AI CORE CONFIG ---
class GroqManager:
    def __init__(self, keys, model_id='llama-3.3-70b-versatile'):
        self.clients = []
        for k in keys:
            if k and not k.startswith('your_secondary_key'):
                try:
                    self.clients.append(Groq(api_key=k))
                    print(f"Groq Client initialized with key: {k[:6]}...{k[-4:]}", flush=True)
                except Exception as e:
                    print(f"Failed to initialize Groq client: {e}", flush=True)
        
        self.current_index = 0
        self.model_id = model_id
        self.logger = logging.getLogger(__name__)

    @property
    def client(self):
        if not self.clients: return None
        return self.clients[self.current_index]

    def rotate(self):
        if len(self.clients) > 1:
            self.current_index = (self.current_index + 1) % len(self.clients)
            self.logger.warning(f"🔄 ROTATING GROQ API KEY -> Slot {self.current_index + 1}")
            print(f"🔄 Rotating Groq API Key to slot {self.current_index + 1}", flush=True)
            return True
        return False

    def call_with_failover(self, method_name, **kwargs):
        """Executes a Groq chat completion with automatic key rotation on failure."""
        if not self.clients: return None
        
        last_error = None
        # Try each client once
        for attempt in range(len(self.clients)):
            client = self.client
            try:
                # Dynamically call the method (usually chat.completions.create)
                if method_name == 'chat.completions.create':
                    # Ensure model is set if not provided
                    if 'model' not in kwargs: kwargs['model'] = self.model_id
                    return client.chat.completions.create(**kwargs)
                elif method_name == 'audio.transcriptions.create':
                    return client.audio.transcriptions.create(**kwargs)
                return None
            except Exception as e:
                last_error = e
                err_msg = str(e).lower()
                self.logger.error(f"Groq Error (Slot {self.current_index + 1}): {err_msg}")
                
                # If it's a rate limit or server error, rotate and retry
                is_retryable = any(x in err_msg for x in ["rate limit", "429", "500", "503", "timeout", "overloaded"])
                if is_retryable and self.rotate():
                    continue
                else:
                    break
        
        self.logger.error(f"Groq Failover Exhausted: {last_error}")
        return None

# Load Keys
GROQ_KEYS = [
    os.environ.get('GROQ_API_KEY'),
    os.environ.get('GROQ_API_KEY_SECONDARY')
]
MODEL_ID = 'llama-3.3-70b-versatile'
groq_manager = GroqManager(GROQ_KEYS, MODEL_ID)

# --- AI CACHE & LOCKING (Quota Preservation) ---
AI_CACHE = {}
AI_PENDING = {} # key -> threading.Event
cache_lock = threading.Lock()

def get_cache_key(prefix, data):
    """Generate a unique key based on the request data."""
    if isinstance(data, dict):
        # Sort keys to ensure consistent hashing
        data_str = json.dumps(data, sort_keys=True)
    else:
        data_str = str(data)
    return f"{prefix}:{hashlib.md5(data_str.encode()).hexdigest()}"

OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'llama3.2')
OLLAMA_AVAILABLE = False

# Check Ollama availability
try:
    ollama_models = ollama_client.list()
    model_names = [m.model for m in ollama_models.models] if ollama_models.models else []
    if any(OLLAMA_MODEL in name for name in model_names):
        OLLAMA_AVAILABLE = True
        print(f"Ollama detected with model '{OLLAMA_MODEL}'. LOCAL AI mode enabled.", flush=True)
    else:
        print(f"Ollama running but model '{OLLAMA_MODEL}' not found. Available: {model_names}", flush=True)
except Exception as e:
    print(f"Ollama not available: {e}. Will use Gemini/fallback.", flush=True)

print(f"AI Engines: Ollama={'ACTIVE' if OLLAMA_AVAILABLE else 'OFF'} | Groq={'ACTIVE' if groq_manager.clients else 'OFF'} ({len(groq_manager.clients)} keys)", flush=True)

def try_ollama_gen(prompt, system_prompt=None):
    """General purpose Ollama generator with JSON support for fallbacks."""
    global OLLAMA_AVAILABLE
    if not OLLAMA_AVAILABLE:
        return None
    try:
        logger.info(f"Ollama Fallback Engine starting for prompt: {prompt[:50]}...")
        messages = []
        if system_prompt:
            messages.append({'role': 'system', 'content': system_prompt})
        messages.append({'role': 'user', 'content': prompt})
        
        response = ollama_client.chat(
            model=OLLAMA_MODEL,
            messages=messages,
            format='json',
            options={'temperature': 0.1}
        )
        text = response.message.content.strip()
        # Robust JSON extraction
        if "```json" in text: text = text.split("```json")[1].split("```")[0].strip()
        elif "```" in text: text = text.split("```")[1].split("```")[0].strip()
        return json.loads(text)
    except Exception as e:
        logger.error(f"Ollama Gen Error: {str(e)}")
        return None

SYSTEM_PROMPT = """
You are a High-Fidelity Professional Data Extraction Engine. Your sole purpose is to transform resume text into a perfectly structured JSON object with ZERO data loss.
You must be EXHAUSTIVE, ensuring that every technical detail, project, and skill mentioned in the text is captured accurately.

CRITICAL DIRECTIVES FOR TOTAL RECALL:
1. ZERO DATA LOSS (SKILLS): You MUST extract every single technical skill, tool, library, framework, and programming language mentioned anywhere in the resume (Skills section, Projects, Experience, Certifications). Do NOT curate or selective-process; if it is a technical term, EXTRACT IT.
2. ZERO DATA LOSS (PROJECTS/EXPERIENCE): Extract EVERY project and job experience. Use the exact verbatim text for descriptions. DO NOT summarize. If a sentence is in the resume, it must be in the description.
3. BIO EXTRACTION: Look for an introductory paragraph. If no "Summary" header exists, use the first biographical paragraph as the "bio". Do NOT truncate.
4. ACADEMIC PRECISION: Extract degree, institution, year, and grade (GPA/Percentage) exactly as written.
5. DETERMINISTIC SORTING: All string arrays (skills, achievements, certifications, softSkills, careerPaths) MUST be sorted alphabetically.
6. METRICS (Mandatory): Generate realistic ATS metrics based on the content.
   - "atsScore": (0-100)
   - "atsBreakdown": evaluative feedback for impact, brevity, structure, and grammar.
   - "profileStrength": (0-100)
   - "scoreReasoning": 3 concise professional bullets.
   - "careerPaths": 3 matching job titles.
   - "recruiterPitch": 2 sentences selling the candidate.

Strict Schema Reference:
{
  "skills": ["Skill 1", "Skill 2"],
  "experience": [{"title": "T", "company": "C", "duration": "D", "description": "Full detail..."}],
  "education": [{"degree": "D", "institution": "I", "year": "Y", "grade": "G"}],
  "projects": [{"title": "T", "description": "Full verbatim detail...", "technologies": ["T1", "T2"], "link": "U"}],
  "achievements": ["A1", "A2"],
  "bio": "FULL VERBATIM SUMMARY.",
  "certifications": ["C1", "C2"],
  "softSkills": ["S1", "S2"],
  "linkedinUrl": "url",
  "githubUrl": "url",
  "atsScore": 85,
  "atsBreakdown": {
    "impact": {"score": 80, "feedback": "..."},
    "brevity": {"score": 90, "feedback": "..."},
    "structure": {"score": 85, "feedback": "..."},
    "grammar": {"score": 95, "feedback": "..."}
  },
  "profileStrength": 78,
  "scoreReasoning": "1... 2... 3...",
  "careerPaths": ["R1", "R2", "R3"],
  "recruiterPitch": "Recruiter-facing pitch..."
}
"""

def parse_with_groq(text):
    if not groq_manager.clients: return None
    try:
        cleaned = clean_text(text)
        prompt = f"{SYSTEM_PROMPT}\n\nResume Text for Extraction:\n{cleaned}"
        print(f"Calling Groq ({MODEL_ID}) for resume parsing...", flush=True)
        
        response = groq_manager.call_with_failover(
            'chat.completions.create',
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            response_format={"type": "json_object"}
        )

        if not response: return None
        text_out = response.choices[0].message.content
        if not text_out: return None
        res_data = json.loads(text_out)
        
        # Post-process
        array_fields = ["skills", "achievements", "certifications", "softSkills", "education", "experience", "careerPaths"]
        for field in array_fields:
            if field in res_data:
                field_val = res_data.get(field)
                if isinstance(field_val, list):
                    if field in ["skills", "achievements", "certifications", "softSkills", "careerPaths"]:
                        res_data[field] = sorted(list(set([str(item).strip() for item in field_val if item])))
                    else:
                        res_data[field] = [item for item in field_val if item]
                else: res_data[field] = []
            else: res_data[field] = []
        
        try: res_data["atsScore"] = int(res_data.get("atsScore", 0))
        except: res_data["atsScore"] = 0
        try: res_data["profileStrength"] = int(res_data.get("profileStrength", 0))
        except: res_data["profileStrength"] = 0
        return res_data
    except Exception as e:
        print(f"Gemini Error: {e}")
        return None

@app.route('/parse', methods=['POST'])
def parse_resume():
    try:
        data = request.get_json() or {}
        text = data.get('text', '')
        if not text: return jsonify({"error": "No text"}), 400
        parsed_data = parse_with_groq(text)
        if parsed_data:
            parsed_data["extractionMethod"] = "AI (Groq)"
        else:
            segments = segment_resume(text)
            parsed_data = {
                "skills": extract_skills(segments, text),
                "education": extract_education(segments, text),
                "experience": [],
                "projects": extract_projects(segments),
                "achievements": [],
                "bio": extract_summary(segments, text),
                "certifications": extract_certifications(segments),
                "softSkills": extract_soft_skills(text),
                "linkedinUrl": extract_links(text)["linkedin"],
                "githubUrl": extract_links(text)["github"],
                "atsScore": 40,
                "extractionMethod": "Local Heuristics"
            }
        return jsonify(parsed_data)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/ai/predict-path', methods=['POST'])
def predict_path():
    try:
        data = request.json or {}
        profile = data.get('profile', {})
        cache_key = get_cache_key("predict-path", profile)
        
        wait_event = None
        with cache_lock:
            if cache_key in AI_CACHE:
                return jsonify(AI_CACHE[cache_key])
            if cache_key in AI_PENDING:
                wait_event = AI_PENDING[cache_key]
            else:
                AI_PENDING[cache_key] = threading.Event()

        if wait_event:
            logger.info("Neural Cache HIT (In-Flight) for predict-path. Waiting...")
            if not wait_event.wait(timeout=45):
                return jsonify({"error": "AI processing timeout"}), 504
            with cache_lock:
                result = AI_CACHE.get(cache_key)
                if result: return jsonify(result)
                return jsonify({"error": "Parallel AI request failed"}), 500

        # We are the Primary executor
        try:
            logger.info(f"Predicting path for profile: {profile.get('skills', [])[:5]}...")
            prompt = f"""
            Analyze this student's professional profile and current placement readiness.
            
            Profile Metrics:
            - Profile Strength (Completeness): {profile.get('profileStrength', 0)}%
            - Technical Skills: {profile.get('skills', [])}
            - Department: {profile.get('department', 'General')}
            
            Based on this, generate a high-fidelity 'Professional Growth Blueprint'. 
            This is NOT just a suggestion; it is a core career strategy.
            
            Provide exactly 3 STRATEGIC PHASES. Each phase must include:
            - 'step': (1, 2, or 3)
            - 'phase': A professional phase name (e.g., 'Phase 1: Foundation & Technical Deep-dive')
            - 'task': A high-level strategic objective.
            - 'detail': A deep, actionable description including specific technical targets or industry standards.
            - 'impact': 'High', 'Medium', or 'Low'.
            - 'duration': Estimated weeks/months (e.g., '4-6 Weeks').
            
            Return ONLY a valid JSON object with the key 'actionPlan'.
            """
            
            ai_data = None
            # Try Groq with Failover
            response = groq_manager.call_with_failover(
                'chat.completions.create',
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1,
                response_format={"type": "json_object"}
            )
            
            if response:
                try:
                    text = response.choices[0].message.content.strip()
                    if "```json" in text: text = text.split("```json")[1].split("```")[0].strip()
                    elif "```" in text: text = text.split("```")[1].split("```")[0].strip()
                    ai_data = json.loads(text)
                except Exception as e:
                    logger.error(f"Failed to parse Groq response: {e}")

            # Fallback to Ollama
            if not ai_data:
                ai_data = try_ollama_gen(prompt)

            if not ai_data:
                return jsonify({"error": "All AI engines failed"}), 503

            with cache_lock:
                AI_CACHE[cache_key] = ai_data
            return jsonify(ai_data)

        finally:
            with cache_lock:
                if cache_key in AI_PENDING:
                    AI_PENDING[cache_key].set()
                    del AI_PENDING[cache_key]

    except Exception as e:
        logger.error(f"Predict Path Final Error: {str(e)}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/ai/analyze-job-fit', methods=['POST'])
def analyze_job_fit():
    try:
        data = request.json or {}
        profile = data.get('studentProfile') or data.get('profile', {})
        job = data.get('job', {})
        cache_key = get_cache_key("job-fit", {"profile": profile, "job": job})
        
        wait_event = None
        with cache_lock:
            if cache_key in AI_CACHE:
                return jsonify(AI_CACHE[cache_key])
            if cache_key in AI_PENDING:
                wait_event = AI_PENDING[cache_key]
            else:
                AI_PENDING[cache_key] = threading.Event()

        if wait_event:
            logger.info("Neural Cache HIT (In-Flight) for job-fit. Waiting...")
            if not wait_event.wait(timeout=45):
                return jsonify({"error": "AI processing timeout"}), 504
            with cache_lock:
                result = AI_CACHE.get(cache_key)
                if result: return jsonify(result)
                return jsonify({"error": "Parallel AI request failed"}), 500

        # Primary Executor
        try:
            logger.info(f"Analyzing job fit for {job.get('title', 'Unknown Job')}...")
            prompt = f"""
            Act as an elite tech recruiter AI. Compare this Student Profile against the Job Description.
            
            Student Skills: {profile.get('skills', [])}
            Student Bio: {profile.get('bio', '')}
            Student CGPA: {profile.get('cgpa', '')}
            
            Job Title: {job.get('title')}
            Job Description: {job.get('description')}
            Required Skills: {job.get('requirements', {}).get('skillsRequired', [])}
            
            Calculate a realistic matchScore (0-100) based on skill overlap. 
            Return ONLY valid JSON:
            {{
                "matchScore": <number>,
                "fitReason": "<2 sentence explanation>",
                "gapAnalysis": "<1 specific missing skill>"
            }}
            """
            
            ai_data = None
            response = groq_manager.call_with_failover(
                'chat.completions.create',
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1,
                response_format={"type": "json_object"}
            )

            if response:
                try:
                    text = response.choices[0].message.content.strip()
                    if "```json" in text: text = text.split("```json")[1].split("```")[0].strip()
                    elif "```" in text: text = text.split("```")[1].split("```")[0].strip()
                    ai_data = json.loads(text)
                except Exception as e:
                    logger.error(f"Failed to parse Groq response: {e}")

            if not ai_data:
                ai_data = try_ollama_gen(prompt)

            if not ai_data:
                return jsonify({"error": "AI Engine failure"}), 503

            with cache_lock:
                AI_CACHE[cache_key] = ai_data
            return jsonify(ai_data)

        finally:
            with cache_lock:
                if cache_key in AI_PENDING:
                    AI_PENDING[cache_key].set()
                    del AI_PENDING[cache_key]

    except Exception as e:
        logger.error(f"Job Fit Final Error: {str(e)}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/ai/audit-project', methods=['POST'])
def audit_project():
    try:
        data = request.json or {}
        project = data.get('project', data)
        prompt = f"Audit project {project.get('title')}: {project.get('description')}. Technologies: {project.get('technologies')}. Return JSON: verificationToken (random hex), verificationSymbol (1 word), auditSummary (1 sentence), complexityScore (0-100)."
        
        ai_data = None
        response = groq_manager.call_with_failover(
            'chat.completions.create',
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            response_format={"type": "json_object"}
        )

        if response:
            try:
                text = response.choices[0].message.content.strip()
                if "```json" in text: text = text.split("```json")[1].split("```")[0].strip()
                elif "```" in text: text = text.split("```")[1].split("```")[0].strip()
                ai_data = json.loads(text)
            except: pass

        if not ai_data:
            try:
                ai_data = try_ollama_gen(prompt)
            except Exception as oe:
                logger.warning(f"Ollama failed in audit_project: {oe}")

        if not ai_data:
            return jsonify({"error": "AI Audit Failed"}), 503
        
        return jsonify(ai_data)
    except Exception as e:
        logger.error(f"Audit Error: {str(e)}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/ai/interview-chat', methods=['POST'])
def interview_chat():
    try:
        data = request.json or {}
        prompt = data.get('prompt', '')
        if not prompt: return jsonify({"error": "No prompt provided"}), 400
        
        ai_response = None
        logger.info(f"Generating interview response using Groq...")
        response = groq_manager.call_with_failover(
            'chat.completions.create',
            messages=[
                {"role": "system", "content": "You are a professional technical interviewer. Keep responses concise (1-3 sentences) and ask one follow-up question."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7
        )
        if response:
            ai_response = response.choices[0].message.content.strip()

        if not ai_response:
            logger.info("Groq failed in interview_chat. Using Ollama fallback (RAW text)...")
            try:
                if OLLAMA_AVAILABLE:
                    resp = ollama_client.chat(
                        model=OLLAMA_MODEL,
                        messages=[
                            {'role': 'system', 'content': 'You are a professional technical interviewer. Keep responses concise (1-3 sentences) and ask one follow-up question.'},
                            {'role': 'user', 'content': prompt}
                        ],
                        options={'temperature': 0.7}
                    )
                    ai_response = resp.message.content.strip()
            except Exception as oe:
                logger.error(f"Ollama raw text fallback error: {oe}")

        if not ai_response:
             return jsonify({"error": "AI Service Not Available"}), 503

        return jsonify({"response": ai_response})
    except Exception as e:
        logger.error(f"Interview Chat Error: {str(e)}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/ai/interview-audio-chat', methods=['POST'])
def interview_audio_chat():
    global client
    try:
        audio_file = request.files.get('audio')
        image_data = request.form.get('image') # Base64 frame for visual presence
        prompt_text = request.form.get('prompt', '')
        
        if not audio_file or not prompt_text:
            return jsonify({"error": "Audio and prompt required"}), 400
            
        audio_bytes = audio_file.read()
        mime_type = audio_file.mimetype or 'audio/webm'
        filename = "audio.webm" if 'webm' in mime_type else "audio.mp4"

        if not audio_bytes or len(audio_bytes) < 100:
            return jsonify({"error": "No audio signal detected. Please check your microphone permissions and try again."}), 400

        logger.info(f"Transcribing audio with Groq Whisper...")
        transcription_res = groq_manager.call_with_failover(
            'audio.transcriptions.create',
            file=(filename, audio_bytes),
            model="whisper-large-v3-turbo",
            response_format="json"
        )
        if not transcription_res:
            return jsonify({"error": "Transcription failed - AI Service Not Available"}), 503
            
        user_speech = transcription_res.text
        
        sys_prompt = f"""
        You are an expert technical recruiter conducting a mock interview.
        Context & Previous Conversation:
        {prompt_text}
        
        Tone: Professional, probing, and high-fidelity.
        Return ONLY valid JSON:
        {{
            "transcription": "{user_speech}",
            "presenceAnalysis": "Camera enabled but visual processing not required here.",
            "response": "<your next question or concise feedback>"
        }}
        """

        logger.info(f"Generating audio interview response using {MODEL_ID}...")
        response = groq_manager.call_with_failover(
            'chat.completions.create',
            messages=[
                {"role": "system", "content": sys_prompt},
                {"role": "user", "content": user_speech}
            ],
            temperature=0.3,
            response_format={"type": "json_object"}
        )
        
        if not response:
            return jsonify({"error": "AI Response Generation failed"}), 503
            
        raw_text = response.choices[0].message.content.strip()
        if "```json" in raw_text: raw_text = raw_text.split("```json")[1].split("```")[0].strip()
        elif "```" in raw_text: raw_text = raw_text.split("```")[1].split("```")[0].strip()
        
        try:
            return jsonify(json.loads(raw_text))
        except json.JSONDecodeError:
            logger.error(f"JSON Decode Error in interview_audio_chat | Raw: {raw_text[:200]}")
            return jsonify({"error": "Malformed AI response", "raw": raw_text[:100]}), 500
    except Exception as e:
        logger.error(f"Interview Audio Chat Error: {str(e)}")
        logger.error(traceback.format_exc())
        return jsonify({"error": str(e)}), 500

@app.route('/api/ai/health', methods=['GET'])
def ai_health():
    """Service health check for frontend and monitoring."""
    return jsonify({
        "status": "online",
        "engines": {
            "groq": f"connected ({len(groq_manager.clients)} keys)" if groq_manager.clients else "offline",
            "ollama": "active" if OLLAMA_AVAILABLE else "inactive"
        },
        "model": MODEL_ID,
        "timestamp": datetime.now().isoformat()
    })

@app.route('/api/ai/evaluate-interview', methods=['POST'])
def evaluate_interview():
    try:
        data = request.json or {}
        conversation = data.get('conversation', [])
        job_title = data.get('jobTitle', 'the role')
        job_description = data.get('jobDescription', '')

        transcript_lines = [f"{('Interviewer' if msg.get('role') == 'system' else 'Candidate')}: {msg.get('content', '')}" for msg in conversation]
        transcript = '\n'.join(transcript_lines)

        if not transcript.strip():
            return jsonify({"error": "No conversation to evaluate"}), 400

        cache_key = get_cache_key("evaluate-interview", {"transcript": transcript, "job": job_title})
        
        wait_event = None
        with cache_lock:
            if cache_key in AI_CACHE:
                return jsonify(AI_CACHE[cache_key])
            if cache_key in AI_PENDING:
                wait_event = AI_PENDING[cache_key]
            else:
                AI_PENDING[cache_key] = threading.Event()

        if wait_event:
            logger.info("Neural Cache HIT (In-Flight) for evaluate-interview. Waiting...")
            if not wait_event.wait(timeout=60): # Evaluation takes longer
                return jsonify({"error": "AI evaluation timeout"}), 504
            with cache_lock:
                result = AI_CACHE.get(cache_key)
                if result: return jsonify(result)
                return jsonify({"error": "Parallel evaluation failed"}), 500

        # Primary Executor
        try:
            logger.info(f"Evaluating interview for {job_title}...")
            prompt = f"""
            Evaluate this interview transcript for the role of {job_title}:
            {transcript}
            
            Return ONLY a valid JSON object:
            {{
                "score": <integer 0-100>,
                "feedback": "<assessment>",
                "strengths": ["<list>"],
                "areasForImprovement": ["<list>"]
            }}
            """
            
            ai_data = None
            response = groq_manager.call_with_failover(
                'chat.completions.create',
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                response_format={"type": "json_object"}
            )

            if response:
                try:
                    text = response.choices[0].message.content.strip()
                    if "```json" in text: text = text.split("```json")[1].split("```")[0].strip()
                    elif "```" in text: text = text.split("```")[1].split("```")[0].strip()
                    ai_data = json.loads(text)
                except: pass

            if not ai_data:
                ai_data = try_ollama_gen(prompt)

            if not ai_data:
                return jsonify({"error": "Interview evaluation failed"}), 503

            # Normalize score
            try: ai_data['score'] = max(0, min(100, int(ai_data.get('score', 70))))
            except: ai_data['score'] = 70

            with cache_lock:
                AI_CACHE[cache_key] = ai_data
            return jsonify(ai_data)

        finally:
            with cache_lock:
                if cache_key in AI_PENDING:
                    AI_PENDING[cache_key].set()
                    del AI_PENDING[cache_key]

    except Exception as e:
        logger.error(f"Evaluate Interview Final Error: {str(e)}")
        return jsonify({"error": str(e)}), 500
def build_chatbot_prompt(full_context, question):
    """Build the system prompt for the chatbot."""
    return f"""You are SPIMS+ Oracle, an intelligent placement management assistant. You help users of a Smart Placement & Internship Management System.

The user is asking a question. Use ONLY the context data below to give a helpful, accurate, and concise answer. Do NOT make up data that isn't in the context.

--- USER CONTEXT ---
{full_context}
--- END CONTEXT ---

User Question: {question}

Rules:
- Be concise but helpful (2-4 sentences max).
- If the user asks about something not in their data, say so honestly.
- If the user is a Student, you can suggest actions like "Check your applications" or "Update your profile".
- If the user is a Recruiter, focus on job/applicant data.
- If the user is a TPO/Faculty, focus on institutional data.
- Never reveal system internals or API details.
- Be conversational and friendly.

Return ONLY valid JSON (no markdown, no code blocks):
{{"reply": "<your response>", "actions": [{{"label": "<button label>", "url": "<in-app route>"}}]}}

The "actions" array should contain 0-2 relevant quick-action buttons. Use real app routes like:
- /student/applications, /student/jobs, /student/profile, /student/interview-prep
- /recruiter/jobs, /recruiter/applications, /recruiter/messages
- /faculty/dashboard, /faculty/students, /faculty/approvals
- /tpo/dashboard, /tpo/students, /tpo/analytics
"""


def try_ollama_chatbot(prompt):
    """Try to get a response from Ollama (local LLM)."""
    global OLLAMA_AVAILABLE
    if not OLLAMA_AVAILABLE:
        return None
    try:
        print(f"Chatbot query using Ollama ({OLLAMA_MODEL})...", flush=True)
        response = ollama_client.chat(
            model=OLLAMA_MODEL,
            messages=[{'role': 'user', 'content': prompt}],
            format='json',
            options={'temperature': 0.5}
        )
        text = response.message.content
        result = json.loads(text)
        # Ensure required keys exist
        if 'reply' not in result:
            result['reply'] = text
        if 'actions' not in result:
            result['actions'] = []
        print(f"Ollama response OK.", flush=True)
        return result
    except Exception as e:
        logger.error(f"Ollama Chatbot Error: {str(e)}")
        return None


def try_groq_chatbot(prompt):
    """Try to get a response from Groq (cloud LLM)."""
    global client
    if not client:
        return None
    try:
        print(f"Chatbot query using Groq ({MODEL_ID})...", flush=True)
        response = client.chat.completions.create(
            model=MODEL_ID,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            response_format={"type": "json_object"}
        )
        result = json.loads(response.choices[0].message.content)
        print(f"Groq response OK.", flush=True)
        return result
    except Exception as e:
        logger.error(f"Groq Chatbot Error: {str(e)}")
        return None


@app.route('/api/ai/chatbot-query', methods=['POST'])
def chatbot_query():
    """AI chatbot with Ollama-first, Gemini-fallback pipeline."""
    try:
        data = request.json or {}
        question = data.get('question', '')
        user_context = data.get('userContext', {})

        if not question.strip():
            return jsonify({"reply": "Please ask me a question!", "actions": []}), 200

        # Build context summary from user data
        role = user_context.get('role', 'User')
        name = user_context.get('name', 'User')
        profile = user_context.get('profile', {})
        applications = user_context.get('applications', [])
        jobs = user_context.get('jobs', [])
        broadcasts = user_context.get('broadcasts', [])

        context_parts = [f"User: {name} (Role: {role})"]

        if profile:
            skills = profile.get('skills', [])
            if skills:
                context_parts.append(f"Skills: {', '.join(skills[:15])}")
            bio = profile.get('bio', '')
            if bio:
                context_parts.append(f"Bio: {bio[:200]}")
            ats = profile.get('atsScore', 0)
            strength = profile.get('profileStrength', 0)
            if ats or strength:
                context_parts.append(f"ATS Score: {ats}, Profile Strength: {strength}")

        if applications:
            app_summary = []
            for app in applications[:5]:
                status = app.get('status', 'unknown')
                job_title = app.get('jobTitle', app.get('job', {}).get('title', 'Untitled'))
                company = app.get('companyName', app.get('job', {}).get('company', 'Unknown'))
                app_summary.append(f"  - {job_title} at {company}: {status}")
            context_parts.append(f"Recent Applications:\n" + "\n".join(app_summary))

        if jobs:
            job_summary = []
            for job in jobs[:5]:
                job_summary.append(f"  - {job.get('title', 'Untitled')} ({job.get('company', 'N/A')}) — {job.get('type', 'Full-time')}")
            context_parts.append(f"Available/Posted Jobs:\n" + "\n".join(job_summary))

        if broadcasts:
            bc_summary = [f"  - {b.get('title', '')}: {b.get('message', '')[:80]}" for b in broadcasts[:3]]
            context_parts.append(f"Recent Broadcasts:\n" + "\n".join(bc_summary))

        full_context = "\n".join(context_parts)
        prompt = build_chatbot_prompt(full_context, question)

        # --- TRY 1: Ollama (Local, Free, Unlimited) ---
        result = try_ollama_chatbot(prompt)
        if result:
            result['engine'] = 'ollama'
            return jsonify(result)

        # --- TRY 2: Groq (Cloud, Crazy Fast) ---
        result = try_groq_chatbot(prompt)
        if result:
            result['engine'] = 'groq'
            return jsonify(result)

        # --- TRY 3: Static Fallback (Always Works) ---
        print("All AI engines unavailable, using static fallback.", flush=True)
        reply = f"Hi {name}! I can see you're a {role}. "
        if applications:
            reply += f"You have {len(applications)} application(s). "
        if jobs:
            reply += f"There are {len(jobs)} job(s) available. "
        reply += "The AI engine is currently warming up. Please try again in a moment."
        return jsonify({"reply": reply, "actions": [], "engine": "fallback"})

    except Exception as e:
        logger.error(f"Chatbot Query Error: {str(e)}")
        return jsonify({"reply": "I'm having trouble processing your request right now. Please try again.", "actions": [], "engine": "error"}), 200


if __name__ == '__main__':
    print(f"Starting High-Precision AI Server (v2.5) on port 8000...")
    app.run(port=8000, host='0.0.0.0', debug=False)
